In [13]:
import numpy as np
import spatial_factorization
from data_loader import load_nsf_slideseq_subset_genes

In [3]:
help(spatial_factorization.SpatialFactorization)

Help on class SpatialFactorization in module spatial_factorization.sf:

class SpatialFactorization(tensorflow.python.module.module.Module)
 |  SpatialFactorization(J, L, Z, lik='poi', psd_kernel=<class 'tensorflow_probability.python.math.psd_kernels.matern.MaternThreeHalves'>, nugget=1e-05, length_scale=0.1, disp='default', nonneg=False, isotropic=True, feature_means=None, **kwargs)
 |
 |  Method resolution order:
 |      SpatialFactorization
 |      tensorflow.python.module.module.Module
 |      tensorflow.python.trackable.autotrackable.AutoTrackable
 |      tensorflow.python.trackable.base.Trackable
 |      builtins.object
 |
 |  Methods defined here:
 |
 |  __init__(self, J, L, Z, lik='poi', psd_kernel=<class 'tensorflow_probability.python.math.psd_kernels.matern.MaternThreeHalves'>, nugget=1e-05, length_scale=0.1, disp='default', nonneg=False, isotropic=True, feature_means=None, **kwargs)
 |      Non-negative process factorization
 |
 |      Parameters
 |      ----------
 |      J 

In [9]:
data = load_nsf_slideseq_subset_genes()

In [10]:
data

AnnData object with n_obs × n_vars = 36536 × 2000
    obs: 'orig.ident', 'nCount_Spatial', 'nFeature_Spatial', 'cells', 'n_genes_by_counts', 'log1p_n_genes_by_counts', 'total_counts', 'log1p_total_counts', 'pct_counts_in_top_50_genes', 'pct_counts_in_top_100_genes', 'pct_counts_in_top_200_genes', 'pct_counts_in_top_500_genes', 'total_counts_mt', 'log1p_total_counts_mt', 'pct_counts_mt', 'n_counts', 'sizefactor'
    var: 'deviance_poisson', 'mt', 'n_cells_by_counts', 'mean_counts', 'log1p_mean_counts', 'pct_dropout_by_counts', 'total_counts', 'log1p_total_counts', 'n_cells'
    uns: 'log1p'
    obsm: 'spatial'
    layers: 'counts'

In [20]:
data.obsm["spatial"][np.random.choice(data.obsm["spatial"].shape[0], 3000, replace=False)].astype("float32")

array([[3487.9 , 4317.3 ],
       [3549.9 ,  889.95],
       [2356.7 , 1789.3 ],
       ...,
       [4269.8 , 4370.3 ],
       [1408.3 , 2597.1 ],
       [5093.4 , 3226.6 ]], dtype=float32)

In [21]:
model = spatial_factorization.SpatialFactorizationHybrid(
    N = data.n_obs,
    J = 2000,
    L = 20,
    Z = data.obsm["spatial"][np.random.choice(data.obsm["spatial"].shape[0], 3000, replace=False)].astype("float32"),
)

ValueError: Error processing property 'trvars_kernel' of _TupleWrapper((<tf.Variable 'gp_kernel/amplitude:0' shape=(10,) dtype=float32, numpy=
array([0.54132485, 0.54132485, 0.54132485, 0.54132485, 0.54132485,
       0.54132485, 0.54132485, 0.54132485, 0.54132485, 0.54132485],
      dtype=float32)>, <tf.Variable 'gp_kernel/length_scale:0' shape=(10,) dtype=float32, numpy=
array([-2.2521687, -2.2521687, -2.2521687, -2.2521687, -2.2521687,
       -2.2521687, -2.2521687, -2.2521687, -2.2521687, -2.2521687],
      dtype=float32)>))